enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
#enabled = false

[Music]
arch = "arm64-v8a"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
#enabled = false

[Spotify]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
#enabled = false

[Twitch]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch"
#enabled = false

[Twitter]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
enabled = false


[TikTok]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
uptodown-dl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
included-patches = "'SIM spoof'"
#enabled = false

[Instagram]
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram"
arch = "arm64-v8a"
#enabled = false
